### ISSUE TITLE
AssertionError: Cannot compare two arrays of different size

### ISSUE THREAD

**Issue by aeeeeeep** [JarvisKevin/mmdet_copypaste_based_on_bboxes#1]
Your work is very nice!, but where I change `mmdet/datasets/pipelines/transformer.py` as you, I meet this error
```python
Original Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/miniconda3/lib/python3.8/site-packages/mmdet-2.25.3-py3.8.egg/mmdet/datasets/dataset_wrappers.py", line 431, in __getitem__
    updated_results = transform(copy.deepcopy(results))
  File "/root/miniconda3/lib/python3.8/site-packages/mmdet-2.25.3-py3.8.egg/mmdet/datasets/pipelines/transforms.py", line 2876, in __call__
    return self._copy_paste(results, selected_results)
  File "/root/miniconda3/lib/python3.8/site-packages/mmdet-2.25.3-py3.8.egg/mmdet/datasets/pipelines/transforms.py", line 2923, in _copy_paste
    updated_dst_masks = self.get_updated_masks(dst_masks, composed_mask)
  File "/root/miniconda3/lib/python3.8/site-packages/mmdet-2.25.3-py3.8.egg/mmdet/datasets/pipelines/transforms.py", line 2956, in get_updated_masks
    assert masks.masks.shape[-2:] == composed_mask.shape[-2:], \
AssertionError: Cannot compare two arrays of different size
```
how should I do? thanks.

**Comment by JarvisKevin** [comment]
I updated the final version of the copypaste based on bbox, maybe you can try it again.

**Comment by JarvisKevin** [comment]
OK, Maybe I know what happened! You may use "Resize" before "Copypaste" in your configuration, which is the official implementation of "copypaste".

**Comment by aeeeeeep** [comment]
this is my train_pipeline config, "Resize" before "Copypaste", I don't know what is the problem
```python
train_pipeline = [                                                                                                                                                                                    
    dict(type='AutoAugment_copy', autoaug_type='v2'),                                                                                                                                                 
    dict(type='Mosaic', img_scale=(1440, 1024), pad_val=114.0),                                                                                                                                       
    dict(                                                                                                                                                                                             
        type='RandomAffine',                                                                                                                                                                          
        scaling_ratio_range=(0.1, 2),                                                                                                                                                                 
        border=(-(1440 // 2), - (1024 // 2))),                                                                                                                                                        
    dict(                                                                                                                                                                                             
        type='MixUp',                                                                                                                                                                                 
        img_scale=(1440, 1024),                                                                                                                                                                       
        ratio_range=(0.8, 1.6),                                                                                                                                                                       
        pad_val=114.0),                                                                                                                                                                               
    dict(type='RandomFlip', flip_ratio=0.5),                                                                                                                                                          
    dict(type='Resize', img_scale=(1440, 1024), keep_ratio=True),                                                                                                                                     
    dict(type='Pad', size_divisor=32),                                                                                                                                                                
    dict(type='CopyPaste', max_num_pasted=100),                                                                                                                                                       
    dict(type='Normalize', **img_norm_cfg),                                                                                                                                                           
    dict(type='DefaultFormatBundle'),                                                                                                                                                                 
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels']),                                                                                                                                     
]
```

**Comment by JarvisKevin** [comment]
The "Resize" should be used in `MultiImageMixDataset`, which means you will get another picture with the same shape in `results['mix_results']`. And your configuration is only resize the picture in `result`.

**Comment by JarvisKevin** [comment]
Maybe you can refer the configuration in  [https://zhuanlan.zhihu.com/p/559940982](url)

**Comment by aeeeeeep** [comment]
OK, thank you very much, now I know why.

**Comment by JarvisKevin** [comment]
It's my pleasure.

**Comment by aeeeeeep** [comment]
I fix all error  finally. But CopyPaste consumes too much CUDA Memory, Before, `batch_size=12`, but when I add CopyPaste, `batch_size=1`, my GPU Memory is 40GB, it's too slowly, so I have to give up this trick.

**Comment by JarvisKevin** [comment]
I'm sorry to hear that! But in my device 2080Ti (11G), I hadn't met your situation. What a terrible operation can boost GPU Memory by 12 times! it's not make sense, isn't it?

**Comment by Audrey528** [comment]
![1669094242251](https://user-images.githubusercontent.com/68552295/203227907-53edd5ab-7dae-46af-8206-bf0c6d67ab4b.png)
I have the same question. I refer the configuration in [https://zhuanlan.zhihu.com/p/559940982](https://github.com/JarvisKevin/mmdet_copypaste_based_on_bboxes/issues/url). 
My config is 
![1669094392110](https://user-images.githubusercontent.com/68552295/203228252-1b67a4f9-42ba-4153-9d36-d4647217f28c.png)
![1669094424547](https://user-images.githubusercontent.com/68552295/203228325-932fe1e9-f2c1-4aa5-8a12-e345646ab017.png)
![1669094466710](https://user-images.githubusercontent.com/68552295/203228446-7ebcea1a-933a-4bcc-b61a-3d508d54dfa4.png)
Can you give me some advice? Thank you.

**Comment by aeeeeeep** [comment]
try to add the secend `dict(type='Resize', img_scale=(1024, 608)),` in front of `dict(type='CopyPaste', max_num_pasted=150),`

**Comment by Audrey528** [comment]
I remove `resize` in load_pipeline, and add `dict(type='Resize', img_scale=(1024, 608)),` in front of `'CopyPaste'`, however it doesn't work.

**Comment by aeeeeeep** [comment]
![22](https://user-images.githubusercontent.com/77915316/203250960-e3d6095f-b31a-430f-990e-4b01e3263b21.png)
I fixed my error by deleting some image augmentation in `train_pipeline`. But your pipeline is so simple, I don't know what's wrong with it. Maybe you can print the size of these different arrays, and modify the code in this green box path according to arrays size.

**Comment by Audrey528** [comment]
OK, Thanks very much, I will try to do this.

**Comment by JarvisKevin** [comment]
@Audrey528 did you fix it? can you post your current configurations?

**Comment by JarvisKevin** [comment]
@aeeeeeep have the OOM problem been found?

**Comment by aeeeeeep** [comment]
> @aeeeeeep have the OOM problem been found?

haven't

**Comment by JarvisKevin** [comment]
@aeeeeeep The config file , I just posted, only use 3833M in my env.

**Comment by Audrey528** [comment]
> @Audrey528 did you fix it? can you post your current configurations?
I haven't solved it. I will post my config. 
```
model = dict(
    type='FasterRCNN',
    backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        norm_cfg=dict(type='BN', requires_grad=True),
        norm_eval=True,
        style='pytorch',
        init_cfg=dict(type='Pretrained', checkpoint='torchvision://resnet50')),
    neck=dict(
        type='FPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        num_outs=5),
    rpn_head=dict(
        type='RPNHead',
        in_channels=256,
        feat_channels=256,
        anchor_generator=dict(
            type='AnchorGenerator',
            scales=[8],
            ratios=[0.5, 1.0, 2.0],
            strides=[4, 8, 16, 32, 64]),
        bbox_coder=dict(
            type='DeltaXYWHBBoxCoder',
            target_means=[0.0, 0.0, 0.0, 0.0],
            target_stds=[1.0, 1.0, 1.0, 1.0]),
        loss_cls=dict(
            type='CrossEntropyLoss', use_sigmoid=True, loss_weight=0.8),
        loss_bbox=dict(type='L1Loss', loss_weight=1.0)),
    roi_head=dict(
        type='StandardRoIHead',
        bbox_roi_extractor=dict(
            type='SingleRoIExtractor',
            roi_layer=dict(type='RoIAlign', output_size=7, sampling_ratio=0),
            out_channels=256,
            featmap_strides=[4, 8, 16, 32]),
        bbox_head=dict(
            type='Shared2FCBBoxHead',
            in_channels=256,
            fc_out_channels=1024,
            roi_feat_size=7,
            num_classes=2,
            bbox_coder=dict(
                type='DeltaXYWHBBoxCoder',
                target_means=[0.0, 0.0, 0.0, 0.0],
                target_stds=[0.1, 0.1, 0.2, 0.2]),
            reg_class_agnostic=False,
            loss_cls=dict(
                type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0),
            loss_bbox=dict(type='CIoULoss', loss_weight=12.0))),
    train_cfg=dict(
        rpn=dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.7,
                neg_iou_thr=0.3,
                min_pos_iou=0.3,
                match_low_quality=True,
                ignore_iof_thr=-1),
            sampler=dict(
                type='RandomSampler',
                num=256,
                pos_fraction=0.5,
                neg_pos_ub=-1,
                add_gt_as_proposals=False),
            allowed_border=-1,
            pos_weight=-1,
            debug=False),
        rpn_proposal=dict(
            nms_pre=2000,
            max_per_img=1000,
            nms=dict(type='nms', iou_threshold=0.7),
            min_bbox_size=0),
        rcnn=dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.5,
                neg_iou_thr=0.5,
                min_pos_iou=0.5,
                match_low_quality=False,
                ignore_iof_thr=-1),
            sampler=dict(
                type='RandomSampler',
                num=512,
                pos_fraction=0.25,
                neg_pos_ub=-1,
                add_gt_as_proposals=True),
            pos_weight=-1,
            debug=False)),
    test_cfg=dict(
        rpn=dict(
            nms_pre=1000,
            max_per_img=1000,
            nms=dict(type='nms', iou_threshold=0.7),
            min_bbox_size=0),
        rcnn=dict(
            score_thr=0.05,
            nms=dict(type='nms', iou_threshold=0.5),
            max_per_img=100)))

# dataset settings
dataset_type = 'VOCDataset'
data_root = '/home/user/LYH_WORKSPACE/data/training_data_V1_20220918/VOC2007/'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
load_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='FilterAnnotations', min_gt_bbox_wh=(1e-2, 1e-2)),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_rgb=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='Pad', size=(1024,608))
]

train_pipeline = [
    dict(type='Resize', img_scale=(1024, 608), keep_ratio=True),
    dict(type='CopyPaste', max_num_pasted=150),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_rgb=True),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels']),
]

test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(1024, 608),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]
train_dataset = dict(
    type='MultiImageMixDataset',
    dataset=dict(
        type=dataset_type,
        ann_file='/home/user/LYH_WORKSPACE/data/training_data_V1_20220918/VOC2007/ImageSets/Main/trainval.txt',
        img_prefix='/home/user/LYH_WORKSPACE/data/training_data_V1_20220918/VOC2007/',
        pipeline=load_pipeline,
        filter_empty_gt=True,
    ),
    pipeline=train_pipeline
    )

data = dict(
    samples_per_gpu=16,
    workers_per_gpu=4,
    train=train_dataset,
    val=dict(
        type=dataset_type,
        ann_file='/home/user/LYH_WORKSPACE/data/training_data_V1_20220918/VOC2007/ImageSets/Main/test.txt',
        img_prefix='/home/user/LYH_WORKSPACE/data/training_data_V1_20220918/VOC2007/',
        pipeline=test_pipeline),
    test=dict(
        type=dataset_type,
        ann_file='/home/user/LYH_WORKSPACE/data/training_data_V1_20220918/VOC2007/ImageSets/Main/test.txt',
        img_prefix='/home/user/LYH_WORKSPACE/data/training_data_V1_20220918/VOC2007/',
        pipeline=test_pipeline))
evaluation = dict(interval=1, metric='mAP')

optimizer = dict(type='AdamW', lr=0.00005, weight_decay=0.10)
optimizer_config = dict(grad_clip=dict(max_norm=35, norm_type=2))
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=1800,
    warmup_ratio=0.0125,
    step=[8, 15])
runner = dict(type='EpochBasedRunner', max_epochs=16)
checkpoint_config = dict(interval=1)
log_config = dict(interval=50, hooks=[dict(type='TensorboardLoggerHook')])
custom_hooks = [dict(type='NumClassCheckHook')]
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = None
resume_from = None
workflow = [('train', 1)]
opencv_num_threads = 0
mp_start_method = 'fork'
auto_scale_lr = dict(enable=False, base_batch_size=16)
gpu_ids = [0]
auto_resume = False
```

**Comment by aeeeeeep** [comment]
> 

I guess because my image size(1440, 1024) is too big in pipeline, then I change it to size(960, 680), It works ok.

**Comment by JarvisKevin** [comment]
@aeeeeeep in my program, the original image size is 5k*4k, I resize it into 2k*2k.

**Comment by aeeeeeep** [comment]
> @aeeeeeep in my program, the original image size is 5k*4k, I resize it into 2k*2k.

It's so strange.

**Comment by JarvisKevin** [comment]
@Audrey528 
```
load_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='Resize', img_scale=(1024, 608), keep_ratio=False),
    dict(type='FilterAnnotations', min_gt_bbox_wh=(1e-2, 1e-2)),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_rgb=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='Pad', size=(1024,608))
]

train_pipeline = [
    dict(type='CopyPaste', max_num_pasted=150),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_rgb=True),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels']),
]
```

**Comment by Audrey528** [comment]
Thanks very much. I change  `keep_ratio=True` to ` keep_ratio=False` in `dict(type='Resize', img_scale=(1024, 608), keep_ratio=False),` the error is solved.  But I have another question, that is the pictures augemented by copypaste are weird. For example, 
![1669246746399](https://user-images.githubusercontent.com/68552295/203722059-4520b9e7-a312-47a6-aaa8-8051880ce0d9.png)

**Comment by XMX969** [comment]
I have the same question. My config is :

load_pipeline = [
    dict(type="LoadImageFromFile", backend_args=backend_args),
    dict(type="LoadAnnotations", with_bbox=True, with_mask=True),
    dict(type="Resize", scale=(1000, 600), keep_ratio=True),
    dict(type="Pad", size=(1000, 600)),
    dict(type="RandomFlip", prob=0.5),
]

train_pipeline = [
    dict(type="Resize", scale=(1000, 600), keep_ratio=True),
    dict(type="deepir.CopyPaste", selected=False),
    dict(type="PackDetInputs"),
]
test_pipeline = [
    dict(type="LoadImageFromFile", backend_args=backend_args),
    dict(type="Resize", scale=(1000, 600), keep_ratio=True, clip_object_border=False),
    dict(type="LoadAnnotations", with_bbox=True),
    dict(
        type="PackDetInputs",
        meta_keys=("img_id", "img_path", "ori_shape", "img_shape", "scale_factor"),
    ),
]
train_dataloader = dict(
    batch_size=2,
    num_workers=2,
    persistent_workers=True,
    sampler=dict(type="DefaultSampler", shuffle=True),
    batch_sampler=dict(type="AspectRatioBatchSampler"),
    dataset=dict(
        type="MultiImageMixDataset",
        dataset=dict(
            type=dataset_type,
            data_root=data_root,
            ann_file="Splits/trainval_v2.txt",
            data_prefix=dict(sub_data_root=""),
            filter_cfg=dict(filter_empty_gt=True, min_size=0, bbox_min_size=0),
            pipeline=load_pipeline,
            backend_args=backend_args,
        ),
        pipeline=train_pipeline,
    ),
)

val_dataloader = dict(
    batch_size=1,
    num_workers=2,
    persistent_workers=True,
    drop_last=False,
    sampler=dict(type="DefaultSampler", shuffle=False),
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        ann_file="Splits/test_v2.txt",
        data_prefix=dict(sub_data_root=""),
        test_mode=True,
        pipeline=test_pipeline,
        backend_args=backend_args,
    ),
)
test_dataloader = val_dataloader

val_evaluator = dict(type="VOCMetric", metric="mAP", eval_mode="area")
test_evaluator = val_evaluator

**Comment by XMX969** [comment]
I have the same question. My config is :

```
# dataset settings
dataset_type = "deepir.SIRSTVOCDetDataset"
data_root = "data/SIRSTdevkit/"

backend_args = None

load_pipeline = [
    dict(type="LoadImageFromFile", backend_args=backend_args),
    dict(type="LoadAnnotations", with_bbox=True, with_mask=True),
    dict(type="Resize", scale=(1000, 600), keep_ratio=True),
    dict(type="Pad", size=(1000, 600)),
    dict(type="RandomFlip", prob=0.5),
]

train_pipeline = [
    dict(type="Resize", scale=(1000, 600), keep_ratio=True),
    dict(type="deepir.CopyPaste", selected=False),
    dict(type="PackDetInputs"),
]
test_pipeline = [
    dict(type="LoadImageFromFile", backend_args=backend_args),
    dict(type="Resize", scale=(1000, 600), keep_ratio=True, clip_object_border=False),
    dict(type="LoadAnnotations", with_bbox=True),
    dict(
        type="PackDetInputs",
        meta_keys=("img_id", "img_path", "ori_shape", "img_shape", "scale_factor"),
    ),
]
train_dataloader = dict(
    batch_size=2,
    num_workers=2,
    persistent_workers=True,
    sampler=dict(type="DefaultSampler", shuffle=True),
    batch_sampler=dict(type="AspectRatioBatchSampler"),
    dataset=dict(
        type="MultiImageMixDataset",
        dataset=dict(
            type=dataset_type,
            data_root=data_root,
            ann_file="Splits/trainval_v2.txt",
            data_prefix=dict(sub_data_root=""),
            filter_cfg=dict(filter_empty_gt=True, min_size=0, bbox_min_size=0),
            pipeline=load_pipeline,
            backend_args=backend_args,
        ),
        pipeline=train_pipeline,
    ),
)

val_dataloader = dict(
    batch_size=1,
    num_workers=2,
    persistent_workers=True,
    drop_last=False,
    sampler=dict(type="DefaultSampler", shuffle=False),
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        ann_file="Splits/test_v2.txt",
        data_prefix=dict(sub_data_root=""),
        test_mode=True,
        pipeline=test_pipeline,
        backend_args=backend_args,
    ),
)
test_dataloader = val_dataloader

val_evaluator = dict(type="VOCMetric", metric="mAP", eval_mode="area")
test_evaluator = val_evaluator
```
